// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_ugdsoKL9_y0htxEyhdun0vFzXWN5LY',
    appId: '1:540817053313:web:2cb520cda9ccb0ba0d9f80',
    messagingSenderId: '540817053313',
    projectId: 'motionmix-50f7d',
    authDomain: 'motionmix-50f7d.firebaseapp.com',
    storageBucket: 'motionmix-50f7d.appspot.com',
    measurementId: 'G-R0FRFX79VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJ0mfegs28pOzqoVRTV9o0LAamuYYUvw',
    appId: '1:540817053313:android:7c456d4bd98040fe0d9f80',
    messagingSenderId: '540817053313',
    projectId: 'motionmix-50f7d',
    storageBucket: 'motionmix-50f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrSAG2JgWWPaJIzzu9aWcQcu2GFUf5smU',
    appId: '1:540817053313:ios:9474ed2f82688f420d9f80',
    messagingSenderId: '540817053313',
    projectId: 'motionmix-50f7d',
    storageBucket: 'motionmix-50f7d.appspot.com',
    iosBundleId: 'com.example.motionMix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrSAG2JgWWPaJIzzu9aWcQcu2GFUf5smU',
    appId: '1:540817053313:ios:9474ed2f82688f420d9f80',
    messagingSenderId: '540817053313',
    projectId: 'motionmix-50f7d',
    storageBucket: 'motionmix-50f7d.appspot.com',
    iosBundleId: 'com.example.motionMix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0_ugdsoKL9_y0htxEyhdun0vFzXWN5LY',
    appId: '1:540817053313:web:86c127aa712073470d9f80',
    messagingSenderId: '540817053313',
    projectId: 'motionmix-50f7d',
    authDomain: 'motionmix-50f7d.firebaseapp.com',
    storageBucket: 'motionmix-50f7d.appspot.com',
    measurementId: 'G-9NRLY0HSVL',
  );
}
